"""
Qwen2-Audio-7B LoRA Fine-tuning for Music Captioning
Dataset : MusicCaps (musiccaps_processed.json)

Architecture overview
---------------------
Base model : Qwen/Qwen2-Audio-7B-Instruct
  - audio_tower   : Whisper-like encoder  → frozen
  - language_model: Qwen2-7B decoder      → LoRA applied (q_proj, k_proj, v_proj, o_proj)
  - multi_modal_projector: linear bridge  → optionally unfrozen

Training strategy (mirrors SALMONN approach)
--------------------------------------------
1. Freeze the entire model.
2. Unfreeze the multi-modal projector (bridges audio → LLM space).
3. Inject LoRA into the LLM's self-attention layers.
4. Compute cross-entropy loss only on the assistant response tokens.
"""

import gc
import os
import json
import torch
import torchaudio
import numpy as np
from dataclasses import dataclass
from typing import Any, Dict, List

# ── Fix 1: reduce VRAM fragmentation (must be set before any CUDA alloc) ────
os.environ.setdefault("PYTORCH_CUDA_ALLOC_CONF", "expandable_segments:True")

from peft import LoraConfig, TaskType, get_peft_model
from transformers import (
    AutoProcessor,
    Qwen2AudioForConditionalGeneration,
    Trainer,
    TrainerCallback,
    TrainingArguments,
)
from torch.utils.data import Dataset

# =====================================================================
# Paths & hyper-parameters
# =====================================================================
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# ── Experiment ID ────────────────────────────────────────────────────────────
# Change this before each new run so TensorBoard shows a readable label.
# Convention: exp-001, exp-002, ...  or  exp-005-r16-lr1e5  for ablations.
EXP_ID = "exp-006"

# Set to a local directory if you have pre-downloaded weights, e.g.:
#   MODEL_ID = "/datas/store163/whyhugo/Qwen2-Audio-7B-Instruct"
MODEL_ID = "Qwen/Qwen2-Audio-7B-Instruct"

# ── Dataset paths ────────────────────────────────────────────────────────────
# Canonical split (80/10/10, seed=42) generated by data/split.py.
# Change these only when running ablations; document the change in experiments/runs.json.
DATA_JSON_TRAIN = os.path.join(PROJECT_ROOT, "data", "musiccaps_train.json")
DATA_JSON_VAL   = os.path.join(PROJECT_ROOT, "data", "musiccaps_val.json")

OUTPUT_DIR  = os.path.join(PROJECT_ROOT, "outputs", "qwen_musiccaps_finetuned")
LOGGING_DIR = os.path.join(OUTPUT_DIR, "runs", EXP_ID)

TARGET_SR      = 16000
MAX_AUDIO_SECS = 30           # truncate audio beyond 30 s
MUSIC_PROMPT   = "Please describe this music in detail and list its aspects."


# =====================================================================
# 1. Dataset
# =====================================================================
class MusicCapsDataset(Dataset):
    """Loads pre-processed MusicCaps JSON and returns raw waveforms."""

    def __init__(self, data_path: str):
        with open(data_path, "r", encoding="utf-8") as f:
            raw = json.load(f)
        self.max_samples = MAX_AUDIO_SECS * TARGET_SR

        # Resolve paths and preflight-check that audio files exist.
        # Failing here (main process, before DataLoader workers start) gives
        # a much cleaner traceback than failing inside a worker process.
        missing = []
        self.data = []
        for item in raw:
            abs_path = os.path.join(PROJECT_ROOT, item["wav_path"].lstrip("./"))
            if os.path.exists(abs_path):
                item = dict(item)          # shallow copy so we can add the key
                item["_abs_wav_path"] = abs_path
                self.data.append(item)
            else:
                missing.append(abs_path)

        if missing:
            preview = "\n  ".join(missing[:5])
            more = f"\n  ...and {len(missing)-5} more" if len(missing) > 5 else ""
            print(
                f"[WARNING] {len(missing)} audio file(s) not found — skipped.\n"
                f"  {preview}{more}\n"
                f"  To download missing clips: python salmonn/download_musiccaps.py --target all\n"
            )
        if not self.data:
            raise RuntimeError(
                "No audio files found. Run: python salmonn/download_musiccaps.py --target all"
            )

        print(f"Dataset: {len(self.data)} samples loaded from {data_path}")

    def __len__(self) -> int:
        return len(self.data)

    def __getitem__(self, idx: int) -> Dict[str, Any]:
        item = self.data[idx]

        wav_path = item["_abs_wav_path"]
        caption  = item["ground_truth_caption"]

        waveform, sr = torchaudio.load(wav_path)

        # Mono
        if waveform.shape[0] > 1:
            waveform = torch.mean(waveform, dim=0, keepdim=True)

        # Resample to 16 kHz
        if sr != TARGET_SR:
            waveform = torchaudio.functional.resample(waveform, sr, TARGET_SR)

        # Truncate
        if waveform.shape[1] > self.max_samples:
            waveform = waveform[:, :self.max_samples]

        return {
            "audio"  : waveform.squeeze(0).numpy(),   # (T,) float32 numpy
            "caption": caption,
        }


# =====================================================================
# 2. Data Collator
# =====================================================================
@dataclass
class MusicCapsCollator:
    """
    Builds batched model inputs with proper label masking.

    Strategy
    --------
    For each sample we create two texts:
      - full_text   : <system>...<user>AUDIO + prompt<assistant>caption<|im_end|>
      - prompt_text : <system>...<user>AUDIO + prompt<assistant>   (generation prompt)

    We process both through the processor (with audio) to get the exact
    number of tokens occupied by the prompt portion (audio tokens included).
    Labels for prompt positions are masked to -100 so loss is computed
    only on the assistant response.
    """

    processor: Any

    def __call__(self, batch: List[Dict]) -> Dict[str, torch.Tensor]:
        audios        = [item["audio"]   for item in batch]
        captions      = [item["caption"] for item in batch]

        full_texts   = []
        prompt_texts = []

        for caption in captions:
            user_content = [
                {"type": "audio"},
                {"type": "text", "text": MUSIC_PROMPT},
            ]
            full_conv = [
                {"role": "user",      "content": user_content},
                {"role": "assistant", "content": caption},
            ]
            prompt_conv = [
                {"role": "user", "content": user_content},
            ]
            full_texts.append(
                self.processor.apply_chat_template(
                    full_conv, tokenize=False, add_generation_prompt=False
                )
            )
            prompt_texts.append(
                self.processor.apply_chat_template(
                    prompt_conv, tokenize=False, add_generation_prompt=True
                )
            )

        # Tokenize full sequences (text + audio features)
        full_inputs = self.processor(
            text=full_texts,
            audio=audios,
            return_tensors="pt",
            padding=True,
            sampling_rate=TARGET_SR,
        )

        # Tokenize prompt-only (same audio) to get exact prompt token length
        # including expanded audio placeholder tokens
        prompt_inputs = self.processor(
            text=prompt_texts,
            audio=audios,
            return_tensors="pt",
            padding=True,
            sampling_rate=TARGET_SR,
        )

        labels = full_inputs["input_ids"].clone()

        for i in range(len(batch)):
            # With right-padding: real tokens occupy [0 : sum(attention_mask)]
            prompt_len = int(prompt_inputs["attention_mask"][i].sum().item())
            full_len   = int(full_inputs["attention_mask"][i].sum().item())

            labels[i, :prompt_len] = -100   # mask prompt (user turn + audio)
            labels[i, full_len:]   = -100   # mask padding

        full_inputs["labels"] = labels

        # Store label ratio for LoraMetricsCallback (works because num_workers=0)
        valid_tokens = (labels != -100).sum().item()
        total_tokens = labels.numel()
        LoraMetricsCallback.last_label_ratio = valid_tokens / max(total_tokens, 1)

        return full_inputs


# =====================================================================
# 3a. Callback: clear VRAM before evaluation
# =====================================================================
class ClearCacheBeforeEvalCallback(TrainerCallback):
    """
    Clears GPU memory fragmentation that accumulates during training
    before each evaluation pass starts.

    Root cause of OOM during eval:
      - Training (grad_accum=8) manages VRAM efficiently via gradient release.
      - At epoch end, Trainer triggers eval with a fresh 100-sample loop.
      - Each eval forward pass keeps activations alive briefly; combined with
        fragmentation from training, this can exceed the 24 GB limit.
    Fix:
      - on_epoch_end fires BEFORE the eval that follows epoch end.
      - gc.collect() + torch.cuda.empty_cache() reclaim fragmented pages.
    """

    def on_epoch_end(self, args, state, control, **kwargs):
        gc.collect()
        torch.cuda.empty_cache()
        torch.cuda.synchronize()

    def on_evaluate(self, args, state, control, **kwargs):
        # Belt-and-suspenders: clear again if called independently
        gc.collect()
        torch.cuda.empty_cache()


# =====================================================================
# 3b. Callback: extra TensorBoard metrics
# =====================================================================
class LoraMetricsCallback(TrainerCallback):
    """
    Appends training-health metrics to the existing TensorBoard logs.

    Since user callbacks run *before* the TensorBoardCallback (which is
    added last via report_to=), values added to `logs` here are picked up
    automatically and written to the event file.

    Metrics
    -------
    train/lora_B_rms  : RMS of all LoRA-B matrices.
                        Starts near 0 (zero-init) and grows as the model adapts.
                        If this stays flat → LoRA is not learning.

    train/lora_A_rms  : RMS of all LoRA-A matrices.
                        Should stay roughly constant (random init, not optimised
                        by default in standard LoRA).

    train/projector_rms : RMS of the multi_modal_projector weights.
                          Should decrease from initial values as it fine-tunes the
                          audio→LLM alignment.

    train/label_ratio : Fraction of sequence positions that carry real loss
                        (i.e. labels != -100).  Sanity-checks the masking logic;
                        expected ≈ 0.02–0.20 for typical caption lengths.
    """

    # Collator stores per-batch stats here (main-process only, num_workers=0)
    last_label_ratio: float = 0.0

    def on_log(self, args, state, control, model=None, logs=None, **kwargs):
        if model is None or logs is None:
            return

        b_sq = b_n = 0.0
        a_sq = a_n = 0.0
        p_sq = p_n = 0.0

        for name, param in model.named_parameters():
            if not param.requires_grad:
                continue
            val = param.data.float().pow(2).sum().item()
            num = param.numel()
            if "lora_B" in name:
                b_sq += val;  b_n += num
            elif "lora_A" in name:
                a_sq += val;  a_n += num
            elif "multi_modal_projector" in name:
                p_sq += val;  p_n += num

        if b_n: logs["train/lora_B_rms"]     = round((b_sq / b_n) ** 0.5, 6)
        if a_n: logs["train/lora_A_rms"]     = round((a_sq / a_n) ** 0.5, 6)
        if p_n: logs["train/projector_rms"]  = round((p_sq / p_n) ** 0.5, 6)

        if self.last_label_ratio:
            logs["train/label_ratio"] = round(self.last_label_ratio, 4)


# =====================================================================
# 3b. Callback: track best val/loss and save best adapter
# =====================================================================
class BestValCheckpointCallback(TrainerCallback):
    """
    Saves the LoRA adapter + projector to checkpoint-best/ whenever
    eval/loss reaches a new minimum.

    Design note — why on_save instead of on_evaluate:
      In transformers 5.x, on_evaluate does NOT reliably receive the
      `model` kwarg (trainer may call it without passing model depending
      on version). on_save always receives model, and with eval_strategy=
      "epoch" + save_strategy="epoch", the save fires right after eval
      in the same epoch-end block.

    Flow per epoch:
      1. Eval runs  →  on_evaluate records val_loss, sets _pending_save=True
      2. Save fires →  on_save sees _pending_save, copies adapter to checkpoint-best/

    save_total_limit note:
      checkpoint-best/ is a SEPARATE directory not managed by save_total_limit,
      so the best adapter is never rotated out even if full checkpoints are.
    """

    def __init__(self):
        self.best_val_loss  = float("inf")
        self.best_step      = -1
        self.history: list  = []          # [(epoch, step, val_loss)]
        self._pending_save  = False       # flag: on_save should copy to checkpoint-best
        self._pending_meta  = {}

    def on_evaluate(self, args, state, control, metrics=None, **kwargs):
        val_loss = (metrics or {}).get("eval_loss", float("inf"))
        self.history.append((round(state.epoch, 2), state.global_step, round(val_loss, 4)))

        if val_loss < self.best_val_loss:
            self.best_val_loss = val_loss
            self.best_step     = state.global_step
            self._pending_save = True
            self._pending_meta = {"step": state.global_step,
                                  "epoch": round(state.epoch, 2),
                                  "val_loss": round(val_loss, 4)}
            print(f"\n[BestVal] ✓ New best  val_loss={val_loss:.4f}  "
                  f"ep={state.epoch:.1f}  step={state.global_step}"
                  f"  (will save adapter on next on_save)")
        else:
            gap = val_loss - self.best_val_loss
            print(f"\n[BestVal]   val_loss={val_loss:.4f}  "
                  f"(best={self.best_val_loss:.4f} @ step {self.best_step}  Δ=+{gap:.4f})")

    def on_save(self, args, state, control, model=None, **kwargs):
        """Fires right after eval in epoch-end block → model is always available."""
        if not self._pending_save or model is None:
            return control

        best_dir = os.path.join(args.output_dir, "checkpoint-best")
        os.makedirs(best_dir, exist_ok=True)

        # Save lightweight LoRA adapter (NOT the full frozen model)
        if hasattr(model.model, "language_model"):
            model.model.language_model.save_pretrained(best_dir)
        if hasattr(model.model, "multi_modal_projector"):
            torch.save(model.model.multi_modal_projector.state_dict(),
                       os.path.join(best_dir, "projector_weights.pt"))

        with open(os.path.join(best_dir, "best_info.json"), "w") as f:
            json.dump(self._pending_meta, f, indent=2)

        print(f"[BestVal]   Adapter saved → {best_dir}  "
              f"(val_loss={self._pending_meta['val_loss']:.4f})")
        self._pending_save = False
        return control

    def on_train_end(self, args, state, control, **kwargs):
        best_dir = os.path.join(args.output_dir, "checkpoint-best")
        print(f"\n{'='*65}")
        print(f"[BestVal] Val loss history (epoch, step, val_loss):")
        for ep, step, loss in self.history:
            marker = " ←best" if step == self.best_step else ""
            print(f"            ep{ep:>5.1f}  step{step:>5}  loss={loss:.4f}{marker}")
        print(f"[BestVal] Best checkpoint : {best_dir}")
        print(f"[BestVal] Evaluate        : python qwen/evaluate_qwen.py "
              f"--lora_path {best_dir}")
        print(f"{'='*65}\n")


# =====================================================================
# 3c. Callback: save PEFT adapter alongside every Trainer checkpoint
# =====================================================================
class SavePeftAdapterCallback(TrainerCallback):
    """
    Saves the LoRA adapter in PEFT format (adapter_config.json +
    adapter_model.safetensors) and the projector weights to each
    Trainer checkpoint directory so that evaluate_qwen.py can load
    them with PeftModel.from_pretrained().

    Without this, Trainer only saves the full model state dict
    (model.safetensors) and PeftModel.from_pretrained() cannot find
    the required adapter_config.json.
    """

    def on_save(self, args, state, control, model=None, **kwargs):
        if model is None:
            return control

        ckpt_dir = os.path.join(args.output_dir, f"checkpoint-{state.global_step}")
        os.makedirs(ckpt_dir, exist_ok=True)

        # Save PEFT adapter (LoRA config + adapter weights only)
        if hasattr(model.model, "language_model"):
            model.model.language_model.save_pretrained(ckpt_dir)
            print(f"\n[Callback] Saved LoRA adapter → {ckpt_dir}/adapter_*.* ")

        # Save projector weights separately (they are not part of the PEFT adapter)
        if hasattr(model.model, "multi_modal_projector"):
            proj_path = os.path.join(ckpt_dir, "projector_weights.pt")
            torch.save(model.model.multi_modal_projector.state_dict(), proj_path)
            print(f"[Callback] Saved projector weights → {proj_path}")

        return control


# =====================================================================
# 3d. Trainer subclass: skip saving the 16 GB frozen base model
# =====================================================================
class LoraTrainer(Trainer):
    """
    Stops Trainer from writing the full ~16 GB `model.safetensors` on every
    checkpoint.

    Why this is needed
    ------------------
    The model handed to Trainer is the full Qwen2AudioForConditionalGeneration
    (≈7 B params, frozen). Only `model.model.language_model` is a PeftModel,
    so HF Trainer's default `_save` serialises the *entire* state dict —
    including the frozen base weights — into a 16 GB file, once per epoch.

    The only weights that actually change (LoRA adapter + multi_modal_projector)
    are already persisted by SavePeftAdapterCallback (~86 MB total), and
    evaluate_qwen.py loads from that PEFT adapter format. The 16 GB file is
    therefore 100 % redundant.

    Overriding `_save` to skip it (while still writing training_args.bin so the
    directory remains a valid checkpoint) shrinks each checkpoint from ~16 GB
    to ~86 MB. Combined with save_only_model=True (no optimizer.pt), the full
    run's footprint drops from ~368 GB to ~2 GB.
    """

    def _save(self, output_dir: str = None, state_dict=None):
        output_dir = output_dir if output_dir is not None else self.args.output_dir
        os.makedirs(output_dir, exist_ok=True)
        # Persist args only — adapter + projector are saved by the callback.
        torch.save(self.args, os.path.join(output_dir, "training_args.bin"))
        print(f"[LoraTrainer] Skipped full base-model save (adapter handled by callback) → {output_dir}")


# =====================================================================
# 4. Model setup
# =====================================================================
def build_model(model_id: str):
    print(f"Loading base model: {model_id}")
    model = Qwen2AudioForConditionalGeneration.from_pretrained(
        model_id,
        torch_dtype=torch.float16,
        device_map="auto",
    )

    # --- Freeze everything ---
    for param in model.parameters():
        param.requires_grad = False

    # --- Unfreeze multi-modal projector (audio → LLM bridge) ---
    # Mirrors SALMONN's speech_llama_proj / speech_Qformer unfreezing
    if hasattr(model.model, "multi_modal_projector"):
        for param in model.model.multi_modal_projector.parameters():
            param.requires_grad = True
            param.data = param.data.to(torch.float32)
        print("Unfrozen: multi_modal_projector")

    # --- Inject LoRA into the LLM backbone (Qwen2-7B decoder) ---
    # Only targets the language_model sub-module so the audio encoder
    # (audio_tower / Whisper encoder) is not modified.
    lora_config = LoraConfig(
        r=16,
        lora_alpha=32,
        target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],
        lora_dropout=0.05,
        bias="none",
        task_type=None,
    )
    model.model.language_model = get_peft_model(model.model.language_model, lora_config)
    model.model.language_model.print_trainable_parameters()

    return model


# =====================================================================
# 5. Main
# =====================================================================
def main():
    processor = AutoProcessor.from_pretrained(MODEL_ID)
    model     = build_model(MODEL_ID)

    print("Building dataset...")

    if not os.path.exists(DATA_JSON_TRAIN):
        raise FileNotFoundError(
            f"Training split not found: {DATA_JSON_TRAIN}\n"
            "Clone the repo and pull to get the committed split files."
        )

    train_dataset = MusicCapsDataset(DATA_JSON_TRAIN)
    val_dataset   = MusicCapsDataset(DATA_JSON_VAL) if os.path.exists(DATA_JSON_VAL) else None
    collator      = MusicCapsCollator(processor=processor)

    if val_dataset:
        print(f"  Train: {len(train_dataset)} samples  |  Val: {len(val_dataset)} samples")
    else:
        print(f"  Train: {len(train_dataset)} samples  |  [WARNING] val split not found")

    # ── exp-006 config ──────────────────────────────────────────────────────
    # Key changes from exp-005b:
    #   data   : train_augmented.json (3162 = 1054 orig + 2108 pitch-shifted ±2st)
    #   val    : val.json (117 clips, same as exp-005b → direct comparison)
    #   epochs : 15 (3162 samples → overfit expected ~ep8-9, val guides real stop)
    # Unchanged: LR=1e-5, grad_clip=0.5, LoRA r=16, all OOM fixes
    # ─────────────────────────────────────────────────────────────────────────
    NUM_EPOCHS  = 15
    total_steps = (len(train_dataset) // 8) * NUM_EPOCHS
    warmup      = max(10, round(total_steps * 0.10))
    print(f"Config: total_steps≈{total_steps}  warmup={warmup}  exp={EXP_ID}")

    training_args = TrainingArguments(
        output_dir=OUTPUT_DIR,
        run_name=EXP_ID,                      # readable label in TensorBoard / W&B
        logging_dir=LOGGING_DIR,              # each EXP_ID gets its own TB folder
        num_train_epochs=NUM_EPOCHS,
        per_device_train_batch_size=1,
        gradient_accumulation_steps=8,        # effective batch = 8
        learning_rate=1e-5,
        max_grad_norm=0.5,
        warmup_steps=warmup,                  # dynamically computed (≈10% of total)
        lr_scheduler_type="cosine",
        fp16=True,
        gradient_checkpointing=True,
        # ── Checkpointing ────────────────────────────────────────────────────
        save_strategy="epoch",
        save_total_limit=None,                # keep ALL checkpoints (best ep may be early)
        save_only_model=True,                 # skip optimizer.pt (~169MB/ckpt); no resume needed
        # ── Evaluation ───────────────────────────────────────────────────────
        eval_strategy="epoch" if val_dataset else "no",
        per_device_eval_batch_size=1,         # explicit; one val sample at a time
        eval_accumulation_steps=8,            # Fix 3: accumulate predictions in chunks
        load_best_model_at_end=False,         # incompatible with device_map="auto"
        # ── Logging ──────────────────────────────────────────────────────────
        logging_steps=10,
        remove_unused_columns=False,
        dataloader_num_workers=0,
        report_to="tensorboard",
    )

    trainer = LoraTrainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=val_dataset,
        data_collator=collator,
        callbacks=[ClearCacheBeforeEvalCallback(), LoraMetricsCallback(),
                   BestValCheckpointCallback(), SavePeftAdapterCallback()],
    )

    import time
    start_time = time.time()

    print("Starting Qwen2-Audio LoRA training...")
    trainer.train()

    end_time = time.time()
    elapsed_sec = end_time - start_time
    elapsed_min = elapsed_sec / 60.0
    elapsed_hr = elapsed_sec / 3600.0

    # Calculate disk usage of checkpoints
    total_bytes = 0
    if os.path.exists(OUTPUT_DIR):
        for root, dirs, files in os.walk(OUTPUT_DIR):
            for f in files:
                fp = os.path.join(root, f)
                try:
                    if os.path.exists(fp) and not os.path.islink(fp):
                        total_bytes += os.path.getsize(fp)
                except Exception:
                    pass
    total_gb = total_bytes / (1024 ** 3)

    # Write a summary JSON
    summary_path = os.path.join(OUTPUT_DIR, f"run_summary_{EXP_ID}.json")
    summary_data = {
        "exp_id": EXP_ID,
        "runtime_seconds": round(elapsed_sec, 2),
        "runtime_minutes": round(elapsed_min, 2),
        "runtime_hours": round(elapsed_hr, 2),
        "total_storage_gb": round(total_gb, 4)
    }
    try:
        os.makedirs(os.path.dirname(summary_path), exist_ok=True)
        with open(summary_path, "w", encoding="utf-8") as f:
            json.dump(summary_data, f, indent=2)
    except Exception as e:
        print(f"[WARNING] Failed to write summary JSON: {e}")

    print(f"\n{'='*65}")
    print(f"Training complete. Checkpoints saved to: {OUTPUT_DIR}")
    print(f"Training Runtime: {elapsed_sec:.2f} seconds ({elapsed_min:.2f} minutes / {elapsed_hr:.2f} hours)")
    print(f"Total storage space used by outputs: {total_gb:.4f} GB")
    if os.path.exists(summary_path):
        print(f"Saved run summary to: {summary_path}")
    print(f"{'='*65}\n")



if __name__ == "__main__":
    main()
